# Generated by Django 4.2.13 on 2024-06-02 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('salary', models.IntegerField()),
                ('hours', models.IntegerField()),
                ('companyid', models.IntegerField()),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
