services:
  listingdb:
    image: mariadb:latest
    container_name: listingdb
    environment:
      MYSQL_ROOT_PASSWORD: listingpass
      MYSQL_DATABASE: individuallistingdb
      MYSQL_USER: quinnlistings
      MYSQL_PASSWORD: listingpass
    ports:
      - "3316:3306"
    networks:
      - linkedtinder
  
  rabbit:
    image: "rabbitmq:3-management"
    container_name: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - linkedtinder
    
  listingbackend:
    build: .
    container_name: listingbackend
    image: individualsem6.azurecr.io/listingbackend:latest
    command: bash -c "python check_db.py --service-name listingdb --ip listingdb --port 3306 && /app/entrypoint.sh"
    volumes:
      - .:/app
    ports:
      - "8020:8020"
    depends_on:
      - listingdb
      - rabbit
    environment:
      - DATABASE_HOST=listingdb
      - DATABASE_NAME=individuallistingdb
      - DATABASE_USER=quinnlistings
      - DATABASE_PASSWORD=listingpass
    networks:
      - linkedtinder

networks: 
  linkedtinder:
    external: true