apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe --file compose.yaml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: listingdb
  name: listingdb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: listingdb
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe --file compose.yaml convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: listingdb
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: individuallistingdb
            - name: MYSQL_PASSWORD
              value: listingpass
            - name: MYSQL_ROOT_PASSWORD
              value: listingpass
            - name: MYSQL_USER
              value: quinnlistings
          image: mariadb:latest
          name: listingdb
          ports:
            - containerPort: 3306
              protocol: TCP
      restartPolicy: Always
