apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe --file compose.yaml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: listingbackend
  name: listingbackend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: listingbackend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe --file compose.yaml convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: listingbackend
    spec:
      containers:
        - args:
            - bash
            - -c
            - python check_db.py --service-name listingdb --ip listingdb --port 3306 && /app/entrypoint.sh
          env:
            - name: DATABASE_HOST
              value: listingdb
            - name: DATABASE_NAME
              value: individuallistingdb
            - name: DATABASE_PASSWORD
              value: listingpass
            - name: DATABASE_USER
              value: quinnlistings
          image: individualsem6.azurecr.io/listingbackend:latest
          name: listingbackend
          ports:
            - containerPort: 8020
              protocol: TCP
          envFrom:
          - configMapRef:
              name: listingbackend-cm0
          volumeMounts:
            - mountPath: /app/config
              name: listingbackend-cm0
      restartPolicy: Always
      volumes:
        - configMap:
            name: listingbackend-cm0
          name: listingbackend-cm0
