apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe --file compose.yaml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: listingbackend
  name: listingbackend
spec:
  ports:
    - name: "8020"
      port: 8020
      targetPort: 8020
  selector:
    io.kompose.service: listingbackend
